---
pins_configuration:
  - id: water_pump
    enabled: true
    pin_name: PB18
    pin_id: 50

  - id: table_lamp
    enabled: true
    pin_name: PE11
    pin_id: 139

sysfs_gpio:
    root_dir: /sys/class/gpio
    abspath: /sys/class/gpio/gpio%s
    relpath: gpio%s
    attrs:
        value: value
        direction: direction

