---
pins_configuration:
  - id: water_pump
    pin_name: PB18
    pin_id: 50
    attrs:
      running_time_msecs: 3000

  - id: table_lamp
    pin_name: PH15
    pin_id: 139

sysfs_gpio:
    root_dir: /sys/class/gpio
    abspath: /sys/class/gpio/gpio%s
    relpath: gpio%s
    attrs:
        value: value
        direction: direction


