F_CPU             = 1000000
BOARD_TAG         = attinyx5
BOARD             = 85
ALTERNATE_CORE    = ATTinyCore
#CORE              = tiny
MCU               = attiny85
OPTIMIZATION_LEVEL = s
CXXFLAGS          += -I. -I/Users/dmitrii/Documents/Arduino/hardware/ATTinyCore/avr/cores/tiny
CFLAGS            += -I. -I/Users/dmitrii/Documents/Arduino/hardware/ATTinyCore/avr/cores/tiny
ARDUINO_CORE_PATH = /Users/dmitrii/Library/Arduino15/packages
include           /usr/local/opt/arduino-mk/Arduino.mk

